dependencies:
  # - <organization/repo><@version (where you say where to get the imported contracts from)
  - smartcontractkit/chainlink-brownie-contracts@1.1.1
compiler:
  solc:
    remappings:
    # saying, whenever you see 'chainlink' it means we're refering to the above package
      - '@chainlink=smartcontractkit/chainlink-brownie-contracts@1.1.1'

dotenv: .env
# adding a list of networks here to pull from into our deploy script; so now we can difine different price feeds for different networks
# so for ex, in this same section (under networks) we can make a new subheading (like we did for rinkeby) called mainnet, and put the mainnet price feed there
networks:
  default: development
  rinkeby: 
    eth_usd_price_feed: "0x8A753747A1Fa494EC906cE90E9f37563A8AF630e"
    verify: TRUE
  mainnet-fork-dev: 
    eth_usd_price_feed: "0x5f4eC3Df9cbd43714FE2740f5E3616155c5b8419"
    verify: FALSE
  development:
    verify: FALSE
  ganache-local:
    verify: FALSE
wallets:
  from_key: ${PRIVATE_KEY}